apiVersion: v1
kind: PersistentVolume
metadata:
  name: extra-pv
spec:
  capacity:
    storage: 38Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  hostPath:
    path: /storage
