apiVersion: v1
kind: Service
metadata:
  name: longhorn-ingress-lb
  namespace: longhorn-system
spec:
  selector:
    app: longhorn-ui
  type: LoadBalancer
  loadBalancerIP: 127.0.0.1
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ingress-lb
  namespace: longhorn-system
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: traefik
  rules:
  - host: longhorn.yonif.net
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: longhorn-frontend
              port:
                number: 80